# Generated by Django 4.0.4 on 2022-04-22 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eHospApp', '0002_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='master',
            old_name='Paasword',
            new_name='Password',
        ),
    ]
