# Generated by Django 4.0.4 on 2022-04-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHospApp', '0003_rename_paasword_master_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(auto_created=True, default='yyyy/mm/dd'),
        ),
    ]
