# Generated by Django 4.0.4 on 2022-04-22 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHospApp', '0006_alter_profile_dob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='DOB',
            field=models.DateField(auto_created=True, default='2020-01-01'),
        ),
    ]
