# Generated by Django 4.0.4 on 2022-05-10 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eHospApp', '0009_profile_profileimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DOB', models.DateField(auto_created=True, default='2020-01-01')),
                ('First_Name', models.CharField(default='', max_length=25)),
                ('Last_Name', models.CharField(default='', max_length=25)),
                ('Gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], max_length=20)),
                ('service', models.CharField(choices=[('DC', 'Dental checkup'), ('FBC', 'Full Body Checkup'), ('EC', 'ENT Checkup'), ('HC', 'Heart Checkup')], max_length=25)),
                ('Date_Time', models.DateField(default='2022-01-01')),
                ('Phone_no', models.IntegerField(max_length=10)),
                ('Email', models.EmailField(max_length=25)),
            ],
        ),
    ]
